# Generated by Django 4.0.6 on 2022-07-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gps', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('street', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
