# Generated by Django 4.0.6 on 2022-08-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='deletion_author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deletion_author', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='marker',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted'), (2, 'Archived')], default=1),
        ),
    ]
