# Generated by Django 4.0.6 on 2022-08-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('map', '0002_marker_deletion_author_marker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='deletion_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deletion_author', to='accounts.userprofile'),
        ),
    ]
